language: node_js
node_js:
  - node
dist: bionic
sudo: required
before_script:
  - npm install -g @angular/cli
script:
  - build_angular.sh
deploy:
  provider: heroku
  api_key: '$HEROKU_TOKEN'
  on: release
notifications:
  email:
    - jingwen92@hotmail.com