language: node_js
node_js:
  - node
dist: bionic
sudo: required
branches:
  only:
    - master
before_script:
  - npm install
  - npm install -g @angular/cli
script:
  - cd angular-src/; ng build --prod; cd ..
deploy:
  provider: heroku
  api_key: '$HEROKU_TOKEN'
  on: production
notifications:
  email:
    - jingwen92@hotmail.com